install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("eurostat")
install.packages("MARSS")
install.packages("vegan")
install.packages("remotes")
remotes::install_github("allisonhorst/palmerpenguins")
